### ISSUE TITLE
Web Support?

### ISSUE THREAD

**Issue by jtkeyva** [OutdatedGuy/cached_video_player_plus#1]
Thanks for this. It says web support, but no other mention of it. Any news appreciated

**Comment by OutdatedGuy** [comment]
Yo @jtkeyva, the plugin works as the normal `video_player` plugin on web as it doesn't provide any caching facilities.

The caching is only available on Android and iOS.

But I think if you want caching on Web, just pass the `Cache-Control` property in the `httpHeaders` attribute of the `CachedVideoPlayerPlusController`.

**Comment by jtkeyva** [comment]
thanks. don't quite understand your proposed solution. also, if you think it does work, seems to make sense to have that as an example included in your package?
thank you

**Comment by OutdatedGuy** [comment]
> thanks. don't quite understand your proposed solution.

Like this:

```dart
controller = CachedVideoPlayerPlusController.network(
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  httpHeaders: {
    'Cache-Control': 'max-age=3600',
  },
)
```

> also, if you think it does work, seems to make sense to have that as an example included in your package?

That's a good idea, I was just updating the package, will add the example too.

**Comment by jtkeyva** [comment]
thaks for updating the docs! i will give this a shot.

been playing with https://pub.dev/packages/video_player_media_kit but unable to get smooth seek/scrolling
