### ISSUE TITLE
Unhandled Exception: PlatformException(VideoError, Failed to load video: Cannot Open, null, null)

### ISSUE THREAD

**Issue by rulefahd** [OutdatedGuy/cached_video_player_plus#10]
Unhandled Exception: PlatformException(VideoError, Failed to load video: Cannot Open, null, null)

**Comment by OutdatedGuy** [comment]
Provide below details for debugging:

1. Output of `flutter doctor -v`
2. Platform
3. Package version

**Comment by chorauoc** [comment]
I am having same issue, this is happening when player try to play video from the cache. I am using latest flutter version

**Comment by OutdatedGuy** [comment]
@chorauoc provide data mentioned in [this comment](https://github.com/OutdatedGuy/cached_video_player_plus/issues/10#issuecomment-1944171102).

**Comment by chorauoc** [comment]
Issue is here seems, but no solution mentioned 

[https://github.com/flutter/flutter/issues/56665#issuecomment-1235279217](link)

Adding this also not resolved this issue

<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>

**Comment by OutdatedGuy** [comment]
Ohhhh. But did the solution from [this comment](https://github.com/OutdatedGuy/cached_video_player_plus/issues/10#issuecomment-1948300217) worked? If you haven't tried it, give it a try and tell me the result.

**Comment by rulefahd** [comment]
> Ok, so the problem is specific to macOS while development as the cache is stored in such a place where VS Code doesn't have access.
> 
> To fix this, give `Full Disk Access` to VS Code
> 
> ```
> Settings -> Privacy & Security -> Full Disk Access -> Allow VS Code
> ```
> 
> Try the above solution and tell me if this works.

I tried it but didn't work

**Comment by OutdatedGuy** [comment]
Can you share result of `flutter run -v` from start till the crash.

**Comment by chorauoc** [comment]
Hi

I will share this today and I want to make a request and that’s can you provide a cache skip Function with downloaded file details so we can check it headers and then send false or true to skip the cache of that url

So internally you can check our function and if false then don’t add it to cache

I think by this way we can avoid others issues if any url have such as header etc

Thanks

**Comment by OutdatedGuy** [comment]
> I want to make a request and that’s can you provide a cache skip Function with downloaded file details so we can check it headers and then send false or true to skip the cache of that url
> 
> So internally you can check our function and if false then don’t add it to cache
> 
> I think by this way we can avoid others issues if any url have such as header etc. Because I cheked this plugin works as expected with correct headers such as video/mp4 etc. But if you have different headers then it not playing from caches
> 
> Thanks

Can you create a new Feature Request Issue? We'll follow that up there.

**Comment by hantrungkien** [comment]
I am having same issue @OutdatedGuy

**Comment by OutdatedGuy** [comment]
@hantrungkien Can you share result of flutter run -v from start till the crash.

**Comment by OutdatedGuy** [comment]
If the plugin is unable to load the video itself _(play from url & even cache)_, it might be a problem with the [video_player](https://pub.dev/packages/video_player) plugin, as this plugin uses [video_player](https://pub.dev/packages/video_player) to play the video. Or could be that the video encoding is not properly supported for the concerned platform.

Else if this plugin is unable to run only the cached video on macOS or iOS **Simulator** during development, this is likely due to access issues for cached file in the IDE/Code Editor.

This won't cause problem in a production app.

Closing as not planned.
