### ISSUE TITLE
Video playback error on hot reload

### ISSUE THREAD

**Issue by adarshneeds** [OutdatedGuy/cached_video_player_plus#11]
I am encountering a video playback error in my Flutter app when using hot reload multiple times. The error message in the console is as follows:

E/flutter ( 1574): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640028, -1, null, [1080, 1920, 29.999134], [-1, -1]), format_supported=YES, null, null)

This error occurs consistently when I hot reload the app multiple times, but the app works fine otherwise. I am using the video player plugin for my app. Any help or suggestions on how to resolve this issue would be greatly appreciated.

**Comment by OutdatedGuy** [comment]
@adarshneeds Please provide below details for me to debug this issue:

1. Development Environment (Linux, macOS, Windows)
2. Output of `flutter doctor -v`
3. Platform (Android, iOS, Linux, macOS, Web, Windows)
4. Package version
5. IDE / Code Editor

**Comment by adarshneeds** [comment]
**Development Environment:** Microsoft Windows [Version 10.0.19045.4046],

**Doctor summary (to see all details, run flutter doctor -v):**
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.4046], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.87.2)
[!] Connected device
    ! No devices available
[√] Network resources

! Doctor found issues in 1 category.

**Platform:** Android

**Package Versions:**

**Flutter:** 3.19.2
**Dart:** 3.3.0 (stable)
**Android SDK:** 34.0.0

**IDE / Code Editor:** VS Code (version 1.87.2)

**Comment by OutdatedGuy** [comment]
Also can you send me the video file you are using to see if there are any issues with the file itself?

**Comment by adarshneeds** [comment]
For `cached_video_player_plus`, I'm using version 2.0.0.

Regarding the emulator, you're right, I'm currently running the app on a real device for testing. The device configuration is:

```
[√] Connected device (1 available)
    • SM F127G (mobile) • RZ8R50AKR5N • android-arm64 • Android 13 (API 33)
```

As for the video file, you can access it [here](https://res.cloudinary.com/trendbrains/video/upload/f_auto:video,q_auto/v1/Tabahi/gods_plan_you_re_exactly_where_you_re_meant_to_be_coding_tech_techvideos_desksetup_softwaredeveloper_softwareengineer_travel_hyderabad_shy1as).

**Comment by OutdatedGuy** [comment]
I'm unable to reproduce this issue on my end. As this issue is stale I'll be closing it now.

If the issue still persists, you can comment again to re-open the issue.
