### ISSUE TITLE
Request to add cache skip function with downloaded file details

### ISSUE THREAD

**Issue by chorauoc** [OutdatedGuy/cached_video_player_plus#12]
Hi,

Can you add cache skip function with downloaded file details. So if any network header issue present then we can skip the cache

Thanks

**Comment by OutdatedGuy** [comment]
Hi @chorauoc, I'm not sure what you mean here. Can you explain the feature you want with more details and examples?

**Comment by chorauoc** [comment]
Hi,

You asked me to raised this as separate request

https://github.com/OutdatedGuy/cached_video_player_plus/issues/10

Thanks
