### ISSUE TITLE
Request to add individual cache clearing method

### ISSUE THREAD

**Issue by chorauoc** [OutdatedGuy/cached_video_player_plus#13]
Hi,

Can you implement a way to remove individual cached video from cache. For example if I pass url to that function it should remove only that vied from the cache 

Thanks

**Comment by OutdatedGuy** [comment]
@chorauoc, nice idea! I'll implement it after I get some free time.

As always PRs are welcomed!

**Comment by chorauoc** [comment]
@OutdatedGuy I have made these changes, so can you give me permission to create pull request. Because I am getting permission error when try to create a pull request. Or you can check the code in attached file and add to your repo

# Added **removeFileFromCache** function to clear cache and get storage entry

# Exposed **getter for isDisposed** to check if player already disposed 

# Added **clearCache** function to clear all cache and get storage

# Added **addListener override method** to prevent exception to be thrown when attempting to add a listener after the controller has already been disposed

# Code refactor

[cached_video_player_plus.dart.zip](https://github.com/OutdatedGuy/cached_video_player_plus/files/14671685/cached_video_player_plus.dart.zip)

**Comment by OutdatedGuy** [comment]
@chorauoc to create a PR you would have to:

1. Fork this repo into your account.
2. Commit the changes into a different branch than main (suppose `feat/clear-cache`)
3. Then push that branch to your fork
4. Then create a PR into this repo from the branch in your fork.
