### ISSUE TITLE
Caching not working on iOS

### ISSUE THREAD

**Issue by cka29** [OutdatedGuy/cached_video_player_plus#20]
Using v.2.0.0 of this package. Android working fine.

However on iOS the `controller.value.isInitialized` is always false and the videos are not loading. It only works if I set `invalidateCacheIfOlderThan: Duration.zero` . I also see this error while debugging
![image](https://github.com/OutdatedGuy/cached_video_player_plus/assets/110424316/2bfc14f4-49d2-4c68-95c4-280737ff1ba4)

EDIT:

**Environment**: macOS
`flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale de-DE)
    • Flutter version 3.19.3 on channel stable at /Users/Shared/fvm/versions/3.19.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (7 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)            
    • iPhone von XXX (mobile)             • X-X           • ios            • iOS 17.4.1 21E236
    • iPhone SE (3rd generation) (mobile) • X-4D82-X-X-C126D7717AE0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 124.0.6367.78

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**IDE**: VSCode
**Platform**: Tested Android and iOS. Only iOS is currently not working when using caching.

**Comment by OutdatedGuy** [comment]
Looks like a similar case to #10

Can you try out [this solution](https://github.com/OutdatedGuy/cached_video_player_plus/issues/10#issuecomment-1948300217) and see what happens?

**Comment by cka29** [comment]
> Looks like a similar case to #10
> 
> Can you try out [this solution](https://github.com/OutdatedGuy/cached_video_player_plus/issues/10#issuecomment-1948300217) and see what happens?

unfortunately did not work... fyi the bug also occurs in production builds on physical devices.

**Comment by OutdatedGuy** [comment]
Ohk, can you send me the video file you are trying to play.

If any privacy reason, then you can share the logs of:

```bash
ffprobe -show_streams -select_streams a /path/to/video
```

**Comment by cka29** [comment]
```
ffprobe version 6.1.1 Copyright (c) 2007-2023 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.1.1_7 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopenvino --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'followme.mov':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2023-06-21T08:43:37.000000Z
  Duration: 00:00:29.24, start: 0.000000, bitrate: 6097 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x676, 6094 kb/s, 25 fps, 25 tbr, 25 tbn (default)
    Metadata:
      creation_time   : 2023-06-21T08:43:37.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : H.264
```

**Comment by OutdatedGuy** [comment]
@cka29

Can you try it with this url: https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
and see if the issue still occurs. So that we can narrow down the possible causes of the problem

**Comment by cka29** [comment]
@OutdatedGuy thanks for the video. With your video it works. Is only mp4 supported on iOS? And why does my video work on android then (even if its .mov) ?

**Comment by cka29** [comment]
@OutdatedGuy now I have uploaded the corrupt video files to a different bucket (google storage) and it seems to work now! Do you know by any chance if there needs to be some specific http headers from the server serving the files?

**Comment by OutdatedGuy** [comment]
> @OutdatedGuy thanks for the video. With your video it works. Is only mp4 supported on iOS? And why does my video work on android then (even if its .mov) ?
> 
> EDIT: I have also tested another .mp4 video on iOS and that didn't work too..

I use `.mp4` files in my own apps and they work just fine. So I think this is a video related issue.

As this package is only a wrapper over the [video_player](https://pub.dev/packages/video_player) package to provide caching mechanism, I can't say much about compatibility issues here. You might want to [file a issue to the official video_player repo](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml) itself for that.

**Comment by OutdatedGuy** [comment]
> @OutdatedGuy now I have uploaded the corrupt video files to a different bucket (google storage) and it seems to work now! Do you know by any chance if there needs to be some specific http headers from the server serving the files?

I don't know about any http header requirement for compatibility. If the video is not corrupt or unsupported, and runs on Android then it should also run on iOS without any changes or issues.

As suggested in the above comment, you might have to file this issue in the official video_player repo.

**Comment by OutdatedGuy** [comment]
Closing as not related!

**Comment by cka29** [comment]
@OutdatedGuy thanks for the hints. After successfully trying your video url I checked the MIME Types of the corrupted video URLs I have used and it turns out that they were application/octet-stream. I changed the MIME type on the server files to video/mp4 instead and then it worked!! Thank you again 🙌🏻

**Comment by OutdatedGuy** [comment]
Glad to know it worked out. Good day!
