### ISSUE TITLE
Would it be possible to condition the caching to video using a boolean?

### ISSUE THREAD

**Issue by indacurdev** [OutdatedGuy/cached_video_player_plus#21]
I am needing to be able to cache or not depending on the case in an application that seeks to play both list videos and live media, for this second case automatic caching is not useful for me, do you think that is possible?

**Comment by OutdatedGuy** [comment]
There is already a PR to enable skipping caching, however looks like the Author of the PR is not updating it.

I'll now update that PR and add this functionality.

Till then you can just use the [video_player](https://pub.dev/packages/video_player) package for live media.
