### ISSUE TITLE
Video controller listeners don't get updated immediately (there's a delay)

### ISSUE THREAD

**Issue by MohanadDaDev** [OutdatedGuy/cached_video_player_plus#34]
I think the delay is about 400-900 ms, (which makes a difference in my app)

this issue/delay doesn't happen in the normal video player package.
this issue/delay happens in both Android and ios.

I think it's because of the old versions of video_player_android and video_player_avfoundation you're using, can you please upgrade them?

**Comment by OutdatedGuy** [comment]
Hi @MohanadDaDev,

> this issue/delay doesn't happen in the normal video player package.
> this issue/delay happens in both Android and ios.

I tried the example app of the `cached_video_player_plus` plugin with the Cached Controller and the normal `video_player` Controller and the result are same (around 2~3 seconds delay, cuz the video file big).

> I think it's because of the old versions of video_player_android and video_player_avfoundation you're using, can you please upgrade them?

The `video_player_android` and `video_player_avfoundation` packages used are with the `^` sign, which means it'll use the latest version which are currently available.

i.e. `video_player_android: >=2.0.0 <3.0.0` and `video_player_avfoundation: >=2.0.0 <3.0.0`

**Comment by MohanadDaDev** [comment]
I see, ok thank you!
