### ISSUE TITLE
Question: Is there any way to set max cacheSize ? and then clean cache with older files when exceeding cachesize ?

### ISSUE THREAD

**Issue by dannyboylx** [OutdatedGuy/cached_video_player_plus#37]
some older Android devices support 1GB max cache ...
thanks in advance

**Comment by OutdatedGuy** [comment]
Hi @dannyboylx, It is not possible with the current caching system. The [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager) does not provide any functionality to set max cacheSize.

All you can do is manually remove cache for video files using the static `removeFileFromCache` function or clear everything using `clearAllCache` function.
