### ISSUE TITLE
there is no video controller !!

### ISSUE THREAD

**Issue by gitkiller444** [OutdatedGuy/cached_video_player_plus#44]
why there is no video controller you have added, this library is doing great while I was testing, but the only problem is there is no way to control video, play/pause, mute/unmute... nothing.. 

But its great to use. just needs some modification. I hope it will be done soon.

**Comment by OutdatedGuy** [comment]
This library does have a controller to play/pause the video. To mute the video you have to invoke the `setVolume` method and set value to zero.

e.g.

```dart
final controller = CachedVideoPlayerPlusController.networkUrl(
  Uri.parse(
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  ),
);

// Invoke below methods after initializing the controller
controller.play(); // Starts playing the video
controller.pause(); // Pauses the video
controller.setVolume(0); // Mutes the video
```
