### ISSUE TITLE
Suggested Functions

### ISSUE THREAD

**Issue by zhuochenming** [OutdatedGuy/cached_video_player_plus#46]
- Cache switch. Allows you to control when the caching feature is enabled.
- Cache video list. Can control the cleaning of specific videos.

By doing this perhaps a better user experience can be provided, thanks!

**Comment by OutdatedGuy** [comment]
Hello @zhuochenming, the features you are mentioning are already present.

1. You can use the `skipCache` flag to control when caching feature is enabled.
2. If you know the url of the video you want to delete, use the static function `removeFileFromCache`.

Let me know if this helps.

**Comment by zhuochenming** [comment]
Thanks, I'll try it.
