### ISSUE TITLE
ExoPlaybackException

### ISSUE THREAD

**Issue by zhangjinhuang** [OutdatedGuy/cached_video_player_plus#49]
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [720, 980, 30.0, ColorInfo(Unset color space, Unset color range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
E/ExoPlayerImplInternal(23894):       at android.os.Handler.dispatchMessage(Handler.java:106)
E/ExoPlayerImplInternal(23894):       at android.os.Looper.loop(Looper.java:219)
E/ExoPlayerImplInternal(23894):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(23894):   Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.hisi.video.decoder.avc
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/ExoPlayerImplInternal(23894):       ... 3 more
E/ExoPlayerImplInternal(23894):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(23894):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/ExoPlayerImplInternal(23894):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:108)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1994)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:873)
E/ExoPlayerImplInternal(23894):       ... 6 more
E/ExoPlayerImplInternal(23894): Disable failed.
E/ExoPlayerImplInternal(23894):   java.lang.IllegalStateException
E/ExoPlayerImplInternal(23894):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal(23894):       at android.media.MediaCodec.flush(MediaCodec.java:2194)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:168)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:960)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:953)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:780)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:794)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:220)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1846)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1566)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1523)
E/ExoPlayerImplInternal(23894):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:686)
E/ExoPlayerImplInternal(23894):       at android.os.Handler.dispatchMessage(Handler.java:106)
E/ExoPlayerImplInternal(23894):       at android.os.Looper.loop(Looper.java:219)
E/ExoPlayerImplInternal(23894):       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by OutdatedGuy** [comment]
Looks like a `video_player` exception. Can try using just the `video_player` plugin to narrow down the cause

**Comment by zhangjinhuang** [comment]
> Looks like a `video_player` exception. Can try using just the `video_player` plugin to narrow down the cause

It's the same problem

**Comment by OutdatedGuy** [comment]
@zhangjinhuang then you need to file this in the [video_player repo issues](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22) cuz this package cannot anything about it.
